### PR TITLE
Do not commit text when reset signal is received

### PR DESCRIPTION
**Pull request by fujiwarat**
ibus-hangul uses ibus_engine_update_preedit_text_with_mode() to
commit the preedit text by ibus-daemon and now focus-out and
mouse click are handled by ibus-daemon and ibus clients.

BUG=https://github.com/ibus/ibus/issues/1980

### CODE REVIEW

**Comment by fujiwarat** [comment]
The ibus side is now upstreamed; https://github.com/ibus/ibus/commit/a40631e166137c9042a68c2d76844e7afc53d388

**Comment by iyagicom** [comment]
Ubuntu supports 1.5.17 on 18.04.
Compiling on Ubuntu is too difficult.
I can not compile and give up.

**Comment by fujiwarat** [comment]
Are there any chances to integrate this patch? ibus 1.5.20 has already been available.

**Comment by fujiwarat** [comment]
If you use Fedora 30, I put ibus-hangul-1.5.1-3.1.fc30.x86_64.rpm with this patch.
https://copr.fedorainfracloud.org/coprs/fujiwara/ibus-hangul-mouse/

**Comment by juhp** [comment]
Ubuntu 18.10+ has ibus-1.5.19

**Comment by fujiwarat** [comment]
Duplicate of #68

**Pull request closed without merging**
