### PR TITLE
Fix reset handling

### PR DESCRIPTION
**Pull request by epico**
In ibus_hangul_engine_reset function, need to call
hangul_ic_reset function also.

URL: https://bugzilla.mozilla.org/show_bug.cgi?id=867433

### CODE REVIEW

**Comment by epico** [comment]
Please review this patch, thanks!

**Comment by choehwanjin** [comment]
libhangul has different convention of reset method.

```
hangul_ic_reset() =! reset
hangul_ic_flush() == reset
```

hangul_ic_reset() will remove the current preedit string without committing it.
hangul_ic_flush() will return the current preedit string in order to commit it.

So hangul_ic_flush() is equivalent of ibus reset method.

Your patch will loose current preedit string on reset method in some input method clients.

**Comment by epico** [comment]
Could you give me some examples of "loose current preedit string on reset method"?

**Comment by choehwanjin** [comment]
How do you test this patch? and which clients did you test with?
Or are there any changes in ibus' reset method implementation?

**Comment by epico** [comment]
I tested with Firefox client.

Steps to reproduce:

Launch Firefox on Fedora 28

1. Turn on Korean IME (iBus1.5.18)
2. Go to the location bar
3. Type "rksk" (가나)
4. Mouse press at the end of text of location bar

Actual results:
The last letter "나" is entered again at the focused position.

Expected results:
"가나" should be entered at the current text of location bar.

**Comment by choehwanjin** [comment]
Try same test with GtkTextView.

I guess firefox may have some special code for reset method.

**Comment by epico** [comment]
Right, GtkTextView has new issues with the patch.

Any suggestions on how to fix this issue?

**Comment by epico** [comment]
@fujiwarat any comments?

**Comment by fujiwarat** [comment]
I think firefox has a bug and probably I think this patch does not fix anything.

I prepare the patches of mouse click; https://github.com/ibus/ibus/issues/1980#issuecomment-414588836

But firefox still outputs the preedit by itself.
E.g.
1. Run firefox
2. Type Ctrl-f and open search box.
3. Type Hangul on both URL box and search box and click each other.

And firefox outputs double characters.

**Comment by epico** [comment]
I suspect that Firefox may have some additional logics for preedit handling,
which will commit the preedit text twice.

To get the Firefox log, try:
$export MOZ_LOG="nsGtkIMModuleWidgets:10"

**Comment by fujiwarat** [comment]
@epico Thank you.
The env variable is useful for me since building firefox spends time and disc space.

My fix is to commit the preedit with mouse click before firefox does anything with focus changes.
Interesting implementation is that firefox uses GtkIMModule of ibus in Wayland while GTK apps use mutter IM module in Wayland.

**Comment by epico** [comment]
@fujiwarat Welcome.

Actually I also noticed that with ibus-libpinyin, the preedit string will commit in Firefox, too.

Although ibus-libpinyin didn't commit the preedit string, I guess Firefox will commit the preedit string for most input methods.

**Comment by epico** [comment]
Actually I just found Firefox will commit the preedit text without input method interaction.

The below patch try to add IBUS_CAP_AUTO_COMMIT flag to Firefox client in ibus.
URL: https://codereview.appspot.com/367850043/

Then ibus-hangul can check the IBUS_CAP_AUTO_COMMIT flag to not commit the preedit text again.
URL: https://github.com/libhangul/ibus-hangul/pull/68/commits/521ec92e915fea7daf5aa00f312e643198f16dd2

Please review the updated patch again, thanks!

**Comment by fujiwarat** [comment]
I don't think this way resolve all the mouse issue.
I think now https://github.com/libhangul/ibus-hangul/pull/73 will fix this issue too.

**Comment by epico** [comment]
Based on Takao Fujiwara's work, I simplified the patch.

When compile with old ibus version, the patch will commit the preedit text
when received the reset signal.

When compile with new ibus version, the patch will not commit the preedit text
when received the reset signal.

Please review it again, thanks!

**Comment by fujiwarat** [comment]
OK, I think now the patch is better than my patch #73.
But I think `ustring_clear(hangul->preedit)` should be called after `hangul_ic_reset(hangul->context)` in ibus_hangul_engine_reset() to follow `PREEDIT_MODE_NONE` mode.

Also please add my comments in the ibus_hangul_engine_reset() besides the commit log:
```
    // ibus-hangul uses
    // ibus_engine_update_preedit_text_with_mode() function which makes
    // the preedit string committed automatically when the reset is received
    // So we don't need to commit the preedit here.
```

**Comment by epico** [comment]
I updated the patch now.
Thanks for the suggestion!

**Comment by changwoo** [comment]
@choehwanjin  Now ibus 1.5.20 is around. Please integrate this and release.  🙏  :+1:

**Comment by choehwanjin** [comment]
This patch checks the compile time version of ibus.
I want to check the run time version of ibus.
Is there any method to check run time version of ibus?

**Comment by changwoo** [comment]
@choehwanjin I suggest reading the version from dconf:

```
$ gsettings get org.freedesktop.ibus.general version
'1.5.19'
$
```

**Comment by fujiwarat** [comment]
@epico Probably I think g_settings_get_value() and g_strsplit() to satisfy the request?

**Comment by epico** [comment]
Okay, I just create another pull request to check ibus version at runtime.

URL: https://github.com/libhangul/ibus-hangul/pull/85

Please review it, thanks!

**Comment by epico** [comment]
Pull request #87 is merged, close this pull request.

**Pull request closed without merging**
