### PR TITLE
Enable hangul mode by default

### PR DESCRIPTION
**Pull request by epico**
When migrate to GSettings, the initial input mode is changed to 'latin',
change the value to 'hangul' by default.

### CODE REVIEW

**Comment by epico** [comment]
Please review the patch, thanks!

**Comment by choehwanjin** [comment]
Previous default value of 'initial_input_mode' was 'INPUT_MODE_LATIN'.
I think we don't need to change it.

**Comment by epico** [comment]
Okay, I see.

**Comment by epico** [comment]
I reverted the change in Fedora, close pull request now.

**Pull request closed without merging**
